// cypress/support/helpers/accountWisePurchaseOrders.js
//
// Helpers for the AccountWise → StockWise PURCHASE-ORDER seam
// (cypress/qa/testPlans/purchaseOrder/AccountWisePoIntegration/plan.md).
//
// A Purchase Order raised in AccountWise has to show up in StockWise's merged
// PO list without any StockWise-side import. These helpers drive AccountWise's
// real purchase API to produce that seed, then read StockWise's merged list
// back, so a spec can assert the two systems agree.
//
// ONE TOKEN, NOT TWO — the single most important thing to get right here.
// `purchase-service` mounts the SAME IAM Keycloak guard StockWise does, so
// the StockWise bearer from cy.login() authenticates directly against it. Do
// NOT copy loginToAccountWise() from ./accountwise.js: that is for the INVOICE
// service (invoice.<host>), which still sits behind the legacy AccountWise
// identity server and needs ACCOUNTWISE_USERNAME / ACCOUNTWISE_PASSWORD. This
// module needs neither. Every parameter below is named `swToken` so a
// mismatched argument is visible at the call site.
//
// The PO NUMBER IS SERVER-GENERATED by AccountWise (generateNextDocumentNumber,
// prefix "PO"), so no caller may choose or predict it — read
// purchase_order_number out of the create response and thread it through every
// assertion.

import poFixture from '../../fixtures/accountWisePurchaseOrder.json';

// Read base URLs lazily and validate on first use, so a misconfigured run fails
// with a named env var instead of an "undefined/..." URL. Same pattern as
// requireEnv() in ./accountwise.js.
function requireEnv(name) {
  const value = Cypress.env(name);
  expect(value, `Cypress env ${name} must be configured`).to.be.a('string').and.not.empty;
  return value;
}

/** AccountWise purchase API base, including the /v1 prefix. */
export const getPurchaseBaseUrl = () => requireEnv('ACCOUNTWISE_PURCHASE_BASE_URL');

/**
 * AccountWise vendor API base. NOTE the `/api/v1` prefix — it differs from the
 * purchase and invoice services' bare `/v1`, and `purchase.<host>/v1/vendor(s)`
 * is a 404. The authoritative service map is the AccountWise SPA's own
 * `/config.json`.
 */
export const getVendorBaseUrl = () => requireEnv('ACCOUNTWISE_VENDOR_BASE_URL');

/**
 * Name of the vendor this suite raises its seed purchase orders against.
 *
 * Configured as a NAME (`ACCOUNTWISE_VENDOR_NAME`), never as a UUID: vendor ids
 * are per-tenant, so a hard-coded id is wrong on every environment except the
 * one it was captured on. Soft default so a config without the key still runs.
 */
export const getPreferredVendorName = () => Cypress.env('ACCOUNTWISE_VENDOR_NAME') || 'Test Vendor';

/** StockWise API base. */
export const getStockWiseApiUrl = () => requireEnv('API_BASE_URL');

/**
 * The dedup/compare key StockWise itself uses.
 *
 * ImportService.getPoList() keys its de-duplication Map on
 * `name.trim().toLowerCase()`, so every membership check in this module must
 * normalise the same way — otherwise a case difference between the two systems
 * reads as "the PO is missing" when it is actually present.
 */
export const poKey = (name) => (name ?? '').toString().trim().toLowerCase();

// ─────────────────────────────────────────────────────────────────────────────
// AccountWise side
// ─────────────────────────────────────────────────────────────────────────────

/**
 * GET {AW}/purchaseOrder/numbers — the exact call StockWise's getPoList() makes
 * server-to-server, issued here with the same bearer.
 *
 * Resolves with the raw Cypress response so callers can distinguish
 * "unreachable / rejected the token" (a suite-level skip) from "reachable but
 * the tenant is empty" (a seeding-level skip). Never throws.
 */
export function getAccountWisePoNumbers(swToken) {
  return cy.request({
    method: 'GET',
    url: `${getPurchaseBaseUrl()}/purchaseOrder/numbers`,
    headers: { Authorization: `Bearer ${swToken}` },
    failOnStatusCode: false,
    timeout: 60000,
  });
}

/**
 * Suite-level reachability probe (plan.md §8 risk 1).
 *
 * StockWise degrades SILENTLY when AccountWise is unreachable — getPoList()
 * races the call against a 5-second timeout and returns the StockWise-only list
 * on failure. Without this probe an AccountWise outage would surface as "the PO
 * is not in the list", sending the reader hunting for a filter bug that does not
 * exist. Resolves with `{ reachable, reason, rows }`.
 */
export function probeAccountWisePurchaseApi(swToken) {
  return getAccountWisePoNumbers(swToken).then((resp) => {
    if (resp.status < 200 || resp.status >= 300) {
      return {
        reachable: false,
        rows: [],
        reason:
          `AccountWise purchase API returned HTTP ${resp.status} for ` +
          `GET ${getPurchaseBaseUrl()}/purchaseOrder/numbers. ` +
          'Either the service is down or it rejected the StockWise bearer — ' +
          'this is an environment signal, not a StockWise regression.',
      };
    }
    const rows = Array.isArray(resp.body?.data) ? resp.body.data : [];
    return { reachable: true, rows, reason: null };
  });
}

/**
 * A vendor reference valid on THIS environment, scraped rather than hard-coded.
 *
 * AccountWise's createPurchaseOrderSchema requires `vendor_id` + `vendor_name`,
 * and vendor UUIDs are per-tenant — a fixture value would be wrong on every
 * environment but the one it was captured on, and a synthetic UUID is rejected
 * by the create endpoint with a **500** (an FK failure surfacing as a server
 * error), which reads as an outage rather than a bad input. So it is always
 * scraped. This mirrors getValidAccountWiseRefs() in ./accountwise.js.
 *
 * DONORS, in order:
 *   1. `GET {vendor}/vendors`, matched on `ACCOUNTWISE_VENDOR_NAME` (default
 *      "Test Vendor") — the dedicated test vendor. Preferred because it does not
 *      require a purchase order to already exist, which would otherwise be a
 *      chicken-and-egg on a fresh tenant.
 *   1b. Any other vendor on the tenant, with a loud warning. Keeps other
 *      environments runnable, but the seeds are then attached to a vendor this
 *      suite does not own.
 *   2. `GET {purchase}/purchaseOrder/numbers` — falls back to reading
 *      vendor_id/vendor_name off any existing PO, for an environment where the
 *      vendor service is unreachable but POs exist.
 *
 * Resolves `{ vendorId, vendorName }`, or **null** when neither donor yields
 * one — callers must this.skip() with a message naming the gap.
 */
export function getAccountWiseVendorRef(swToken) {
  return cy.request({
    method: 'GET',
    url: `${getVendorBaseUrl()}/vendors`,
    headers: { Authorization: `Bearer ${swToken}` },
    failOnStatusCode: false,
    timeout: 60000,
  }).then((resp) => {
    const vendors = (resp.body?.list ?? resp.body?.data?.list ?? []).filter((v) => v?.id);
    const wanted = getPreferredVendorName().trim().toLowerCase();

    // Prefer the CONFIGURED test vendor, matched by name. Taking whichever
    // vendor happens to sort first would silently raise seed purchase orders
    // against a real supplier's record the moment somebody adds a second vendor
    // to the tenant.
    const named = vendors.find((v) => (v.name ?? '').trim().toLowerCase() === wanted);
    if (named) return { vendorId: named.id, vendorName: named.name };

    if (vendors.length) {
      // Named vendor absent: fall back so other environments still run, but say
      // so loudly — the seeds are now attached to somebody else's vendor.
      Cypress.log({
        name: 'getAccountWiseVendorRef',
        message:
          `No vendor named "${getPreferredVendorName()}" on this tenant; falling back to ` +
          `"${vendors[0].name}". Create the test vendor, or set ACCOUNTWISE_VENDOR_NAME.`,
      });
      return { vendorId: vendors[0].id, vendorName: vendors[0].name ?? 'Unknown Vendor' };
    }

    // Fall back to scraping an existing purchase order.
    return probeAccountWisePurchaseApi(swToken).then(({ reachable, rows }) => {
      if (!reachable) return null;
      const donor = rows.find((r) => r?.vendor_id) ?? null;
      if (!donor) return null;
      return { vendorId: donor.vendor_id, vendorName: donor.vendor_name ?? 'Unknown Vendor' };
    });
  });
}

/**
 * Creates a Purchase Order in AccountWise and resolves with its `data` block
 * (id, purchase_order_number, total_amount, …).
 *
 * `status` selects the EP partition under test ('Pending' is the default
 * happy-path partition; 'Draft' is SW-AWPO-API-TC04's). `overrides` is merged
 * shallowly over the fixture template for negative/edge bodies.
 */
export function createAccountWisePo(swToken, { vendorRef, status = 'Pending', quantity, price, overrides = {} } = {}) {
  expect(vendorRef?.vendorId, 'createAccountWisePo needs a vendor reference — call getAccountWiseVendorRef() and skip when it is null').to.exist;

  const template = JSON.parse(JSON.stringify(poFixture.template));
  const line = poFixture.lineItem.epSingleUnit;

  const body = {
    ...template,
    // `order_id` IS REQUIRED, but AccountWise's server-side Joi schema does NOT
    // declare it — POSTing an empty body lists 13 required fields and order_id
    // is not among them. Omit it and the request is accepted by validation and
    // then dies inside the service with a bare
    // `500 {"code":"INTERNAL_SERVER_ERROR"}` and no detail. Only the SPA's own
    // client-side schema states the truth ("Order ID is required!"). This cost
    // an afternoon of probing; do not "simplify" it away.
    order_id: buildSeedOrderId(),
    vendor_id: vendorRef.vendorId,
    vendor_name: vendorRef.vendorName,
    status,
    purchase_order_date: new Date().toISOString().slice(0, 10),
    items: template.items.map((item) => ({
      ...item,
      quantity: quantity ?? line.quantity,
      price: price ?? line.price,
    })),
    ...overrides,
  };

  return cy.request({
    method: 'POST',
    url: `${getPurchaseBaseUrl()}/purchaseOrder`,
    headers: { Authorization: `Bearer ${swToken}` },
    body,
    failOnStatusCode: false,
    timeout: 60000,
  }).then((resp) => {
    expect(
      resp.status,
      `AccountWise must accept the seed purchase order (body: ${JSON.stringify(resp.body?.error ?? resp.body).slice(0, 400)})`,
    ).to.be.within(200, 299);
    const data = resp.body?.data ?? resp.body;
    expect(
      data?.purchase_order_number,
      'AccountWise must return the server-generated purchase_order_number — no test may choose it',
    ).to.exist;
    // `id` is what EVERY teardown and mutation keys off. Without this assertion a
    // renamed identifier field would make deleteAccountWisePo() short-circuit on
    // a falsy id and silently leak every seed, with no log line to notice.
    expect(
      data?.id,
      'AccountWise must return the purchase order id — teardown and every mutation key off it',
    ).to.exist;
    return data;
  });
}

/**
 * Deletes a seed PO from AccountWise (a soft delete). Best-effort and never
 * throws: a failed cleanup must not turn a passing test red, but it MUST be
 * attempted — a leaked seed permanently changes the merged list and would flip
 * the dedup (API-TC08) and sort (API-TC10) assertions on the NEXT run.
 */
export function deleteAccountWisePo(swToken, poId) {
  if (!poId) return cy.wrap(null, { log: false });
  return cy.request({
    method: 'DELETE',
    url: `${getPurchaseBaseUrl()}/purchaseOrder/${poId}`,
    headers: { Authorization: `Bearer ${swToken}` },
    failOnStatusCode: false,
    timeout: 60000,
  }).then((resp) => {
    if (resp.status < 200 || resp.status >= 300) {
      Cypress.log({
        name: 'deleteAccountWisePo',
        message: `Cleanup of AccountWise PO ${poId} returned HTTP ${resp.status} — seed may leak.`,
      });
    }
    return null;
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// StockWise side
// ─────────────────────────────────────────────────────────────────────────────

/**
 * GET {SW}/excel/po-numbers — the merged list under test.
 *
 * Resolves with the `poList` array. Its ELEMENT SHAPE DIFFERS BY QUERY: plain
 * strings by default, `{ name, cost }` with `cost=true`, `{ name, source }`
 * with `source=true`. Use poListNames() rather than reading elements directly.
 */
export function getStockWisePoList(swToken, { close, cost, source } = {}) {
  const params = [];
  if (close !== undefined) params.push(`close=${close}`);
  if (cost !== undefined) params.push(`cost=${cost}`);
  if (source !== undefined) params.push(`source=${source}`);
  const query = params.length ? `?${params.join('&')}` : '';

  return cy.request({
    method: 'GET',
    url: `${getStockWiseApiUrl()}/excel/po-numbers${query}`,
    headers: { Authorization: `Bearer ${swToken}` },
    failOnStatusCode: false,
    // The merged list races a 5s AccountWise call on top of a full
    // purchaseOrders scan; shared QA can be slow.
    timeout: 120000,
  }).then((resp) => {
    expect(resp.status, `GET /excel/po-numbers${query} must succeed`).to.eq(200);
    const poList = resp.body?.data?.poList;
    expect(poList, 'GET /excel/po-numbers must return data.poList as an array').to.be.an('array');
    return poList;
  });
}

/** Normalised names from a poList, shape-agnostic (see getStockWisePoList). */
export const poListNames = (poList) =>
  (poList ?? []).map((entry) => poKey(typeof entry === 'object' ? entry?.name : entry));

/** Whether a PO number is present in a poList, using StockWise's own dedup key. */
export const poListIncludes = (poList, poNumber) => poListNames(poList).includes(poKey(poNumber));

/**
 * Raw (non-asserting) read of the merged list.
 *
 * `getStockWisePoList` asserts a 200 and is what most TCs want. `SW-AWPO-API-TC09`
 * exists precisely to assert that the request SUCCEEDS, so it must be able to see
 * a non-200 rather than have the helper throw first — otherwise the failure
 * message would come from the helper, not from the test's own assertion.
 */
export function getStockWisePoListResponse(swToken, { close, cost, source } = {}) {
  const params = [];
  if (close !== undefined) params.push(`close=${close}`);
  if (cost !== undefined) params.push(`cost=${cost}`);
  if (source !== undefined) params.push(`source=${source}`);
  const query = params.length ? `?${params.join('&')}` : '';

  return cy.request({
    method: 'GET',
    url: `${getStockWiseApiUrl()}/excel/po-numbers${query}`,
    headers: { Authorization: `Bearer ${swToken}` },
    failOnStatusCode: false,
    timeout: 120000,
  });
}

/** The entry for `poNumber` in a poList, shape-agnostic. Undefined when absent. */
export const poListEntry = (poList, poNumber) =>
  (poList ?? []).find(
    (entry) => poKey(typeof entry === 'object' ? entry?.name : entry) === poKey(poNumber),
  );

/** How many times `poNumber` appears — `SW-AWPO-API-TC08` asserts exactly one. */
export const poListCount = (poList, poNumber) =>
  poListNames(poList).filter((n) => n === poKey(poNumber)).length;

// ─────────────────────────────────────────────────────────────────────────────
// AccountWise mutations
// ─────────────────────────────────────────────────────────────────────────────

/**
 * `POST {AW}/purchaseOrder/close` — despite the name this is a **setter** for
 * `metadata.stockWiseStatus`, taking `{ id, stockWiseStatus }`. That is what
 * gives `SW-AWPO-API-TC05`/`TC06` a genuine inverse: pass `'close'` to close,
 * `'open'` to restore.
 *
 * ⚠️ The accepted values are `open` | **`close`** — NOT `'closed'`. AccountWise
 * rejects anything else with
 * `400 "stockWiseStatus" must be one of [open, close]`, while StockWise's own
 * filter compares against `'open'`, so any non-`open` value lands in the same
 * excluded bucket. Both facts verified live 2026-08-18; omitting either field
 * returns `400 "…is required"`.
 */
export const AW_STOCKWISE_STATUS = { OPEN: 'open', CLOSED: 'close' };

export function setAccountWiseStockWiseStatus(swToken, poId, stockWiseStatus) {
  expect(poId, 'setAccountWiseStockWiseStatus needs the AccountWise PO id').to.exist;
  return cy.request({
    method: 'POST',
    url: `${getPurchaseBaseUrl()}/purchaseOrder/close`,
    headers: { Authorization: `Bearer ${swToken}` },
    body: { id: poId, stockWiseStatus },
    failOnStatusCode: false,
    timeout: 60000,
  }).then((resp) => {
    expect(
      resp.status,
      `AccountWise must accept stockWiseStatus='${stockWiseStatus}' (body: ${JSON.stringify(resp.body?.error ?? resp.body).slice(0, 300)})`,
    ).to.be.within(200, 299);
    return resp.body?.data ?? resp.body;
  });
}

/**
 * `POST {AW}/purchaseOrder/cancelPurchaseOrder` — moves the document to
 * `Cancelled`. There is NO inverse in `purchase-service`, so any PO this is
 * called on must be disposable and deleted in `after()` (plan.md §6.3).
 */
export function cancelAccountWisePo(swToken, poId) {
  expect(poId, 'cancelAccountWisePo needs the AccountWise PO id').to.exist;
  return cy.request({
    method: 'POST',
    url: `${getPurchaseBaseUrl()}/purchaseOrder/cancelPurchaseOrder`,
    headers: { Authorization: `Bearer ${swToken}` },
    body: { id: poId },
    failOnStatusCode: false,
    timeout: 60000,
  }).then((resp) => {
    expect(
      resp.status,
      `AccountWise must accept the cancellation (body: ${JSON.stringify(resp.body?.error ?? resp.body).slice(0, 300)})`,
    ).to.be.within(200, 299);
    return resp.body?.data ?? resp.body;
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// StockWise-native purchase orders (the other half of the dedup / Closed cases)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * `POST {SW}/purchase-orders` — unlike AccountWise this accepts an explicit
 * `poNumber`, which is the only way to make the two systems collide on purpose
 * (`SW-AWPO-API-TC08` dedup, `SW-AWPO-API-TC11` StockWise-Closed).
 */
export function createStockWisePo(swToken, { poNumber, status = 'Open', expectedQuantity = 1 } = {}) {
  expect(poNumber, 'createStockWisePo needs a poNumber').to.be.a('string').and.not.empty;
  return cy.request({
    method: 'POST',
    url: `${getStockWiseApiUrl()}/purchase-orders`,
    headers: { Authorization: `Bearer ${swToken}` },
    body: { poNumber, status, expectedQuantity },
    failOnStatusCode: false,
    timeout: 60000,
  }).then((resp) => {
    expect(
      resp.status,
      `StockWise must accept the counterpart PO "${poNumber}" (body: ${JSON.stringify(resp.body).slice(0, 300)})`,
    ).to.be.within(200, 299);
    return resp.body?.data ?? resp.body;
  });
}

/**
 * Make sure StockWise has a counterpart row for `poNumber`, WITHOUT ever
 * mutating or deleting a purchase order this suite did not create.
 *
 * Why this is not just `createStockWisePo`: AccountWise restarts its numbering
 * (`PO-0001`, `PO-0002`, …) whenever its tenant is emptied, and shared QA's
 * StockWise already holds native purchase orders in exactly that range. So the
 * AccountWise-generated number is USUALLY already taken, and a plain create
 * returns `400 "Duplicate purchase order number detected"` — which is a fact
 * about the environment, not a defect (this is what made TC08/TC11 fail on
 * their first run).
 *
 * Resolves `{ mode, status }`:
 *   • `created` — the number was free; we made it, and the caller must delete it.
 *   • `reused`  — a StockWise row already existed with an acceptable status.
 *                 NOT registered for deletion: it is somebody else's data.
 *   • `unusable`— a row exists but its status is not the one the test needs, and
 *                 changing it would mutate shared data (closing a purchase order
 *                 also writes stockWiseStatus back into AccountWise). The caller
 *                 must this.skip() rather than force it.
 */
export function ensureStockWiseCounterpart(swToken, poNumber, { requiredStatus = null } = {}) {
  return getStockWisePoDetail(swToken, poNumber).then((detail) => {
    const row = detail.body?.data ?? null;
    const existingStatus = row?.poNumber ? row.status : null;

    if (!existingStatus) {
      return createStockWisePo(swToken, {
        poNumber,
        status: requiredStatus ?? 'Open',
      }).then(() => ({ mode: 'created', status: requiredStatus ?? 'Open' }));
    }
    if (!requiredStatus || existingStatus === requiredStatus) {
      return { mode: 'reused', status: existingStatus };
    }
    return { mode: 'unusable', status: existingStatus };
  });
}

/** Best-effort teardown of a StockWise-native PO. Never throws. */
export function deleteStockWisePo(swToken, poNumber) {
  if (!poNumber) return cy.wrap(null, { log: false });

  const del = () =>
    cy.request({
      method: 'DELETE',
      url: `${getStockWiseApiUrl()}/purchase-orders/${encodeURIComponent(poNumber)}`,
      headers: { Authorization: `Bearer ${swToken}` },
      failOnStatusCode: false,
      timeout: 60000,
    });

  return del().then((resp) => {
    if (resp.status >= 200 && resp.status < 300) return null;

    // A Closed purchase order CANNOT be deleted — PurchaseOrdersService.delete
    // throws `Cannot delete PO …: It is closed`. SW-AWPO-API-TC11 creates its
    // counterpart Closed on purpose, so without this its row would survive every
    // run, permanently occupying that number in StockWise. Since a stuck Closed
    // row is itself the "number collision" the rest of the suite has to skip
    // around, the suite would degrade its own environment run over run.
    // Reopen (the documented inverse) and retry once.
    const closed = /is closed/i.test(JSON.stringify(resp.body ?? ''));
    if (!closed) {
      Cypress.log({
        name: 'deleteStockWisePo',
        message: `Cleanup of StockWise PO ${poNumber} returned HTTP ${resp.status} — row may leak.`,
      });
      return null;
    }
    return cy.request({
      method: 'PATCH',
      url: `${getStockWiseApiUrl()}/purchase-orders/reopenPurchaseOrder`,
      headers: { Authorization: `Bearer ${swToken}` },
      body: { poNumber, status: 'Open' },
      failOnStatusCode: false,
      timeout: 60000,
    }).then(() => del()).then((retry) => {
      if (retry.status < 200 || retry.status >= 300) {
        Cypress.log({
          name: 'deleteStockWisePo',
          message: `Cleanup of StockWise PO ${poNumber} failed even after reopen (HTTP ${retry.status}) — row WILL leak and will occupy that PO number.`,
        });
      }
      return null;
    });
  });
}

/**
 * `POST {SW}/purchase-orders/create/ingest` — the push-side counterpart, where
 * AccountWise writes a PO row into StockWise directly. Returns the raw response
 * so `SW-AWPO-API-TC12` can assert the created shape and `TC13` the duplicate
 * rejection, without the helper deciding which is a failure.
 */
export function ingestAccountWisePo(swToken, payload, { noAuth = false } = {}) {
  return cy.request({
    method: 'POST',
    url: `${getStockWiseApiUrl()}/purchase-orders/create/ingest`,
    headers: noAuth
      ? { 'Content-Type': 'application/json' }
      : { Authorization: `Bearer ${swToken}`, 'Content-Type': 'application/json' },
    body: payload,
    failOnStatusCode: false,
    timeout: 60000,
  });
}

/**
 * Every purchase order this suite creates carries this prefix in its `order_id`,
 * which is how sweepSuiteSeeds() tells our disposable seeds apart from real
 * AccountWise data. Never widen it.
 */
export const SUITE_ORDER_ID_PREFIX = 'CYP-PO-';

/**
 * Identifies the seeds created by THIS spec file's run.
 *
 * Cypress boots a fresh module registry per spec, so this is per-spec — which is
 * exactly the granularity the sweep needs: `AccountWisePoIntegrationAPI.cy.js`
 * and `AccountWisePoIntegration.cy.js` both sweep the same shared tenant, and a
 * prefix-only sweep would let either one delete the other's LIVE seeds the
 * moment the two run concurrently (Cypress parallelisation, or two engineers on
 * the same QA tenant). Ownership plus an age floor is what makes the sweep safe
 * to run at any time — see sweepSuiteSeeds().
 */
const RUN_ID = `r${Date.now().toString(36)}${Math.floor(Math.random() * 1e6).toString(36)}`;

/** `CYP-PO-<runId>-<epochMs>-<rand>` — the order_id stamped on every seed. */
export const buildSeedOrderId = () =>
  `${SUITE_ORDER_ID_PREFIX}${RUN_ID}-${Date.now()}-${Math.floor(Math.random() * 1e6)}`;

/**
 * How old ANOTHER run's seed must be before this run may delete it. Long enough
 * to outlast a full execution of either spec, short enough that a re-run later
 * in the same session still self-heals. Override with
 * `--env AWPO_SEED_MAX_AGE_MINUTES=<n>`.
 */
const getSeedSweepMinAgeMs = () =>
  Number(Cypress.env('AWPO_SEED_MAX_AGE_MINUTES') ?? 20) * 60 * 1000;

/** `{ runId, createdAt }` for one of our order_ids, or null when it is not ours. */
function parseSeedOrderId(orderId) {
  const raw = (orderId ?? '').toString();
  if (!raw.startsWith(SUITE_ORDER_ID_PREFIX)) return null;
  const parts = raw.slice(SUITE_ORDER_ID_PREFIX.length).split('-');
  // Seeds left on the tenant by a build that predates RUN_ID read
  // `<epochMs>-<rand>`. They belong to no live run, so they are always sweepable.
  const legacy = /^\d+$/.test(parts[0] ?? '');
  const createdAt = Number(legacy ? parts[0] : parts[1]);
  return {
    runId: legacy ? null : parts[0],
    createdAt: Number.isFinite(createdAt) && createdAt > 0 ? createdAt : null,
  };
}

/**
 * Delete the AccountWise purchase orders this suite has left behind, and nothing
 * else.
 *
 * Called from `before()` rather than relying on teardown, because Cypress's
 * `this.skip()` aborts a test AND its remaining hooks — `afterEach` and `after`
 * included — so a seed created just before a skip is never torn down by them.
 * Sweeping at the start makes each run self-healing regardless of how the
 * previous one ended.
 *
 * A row is deleted when it carries this suite's `order_id` prefix AND either
 *   • it belongs to THIS spec's run (`RUN_ID`) — always safe, it is ours; or
 *   • it is older than getSeedSweepMinAgeMs(), so no live run can still be
 *     asserting on it.
 * Anything else is left alone and logged, which is what keeps the sweep safe when
 * the API and UI specs run at the same time against one shared tenant.
 */
export function sweepSuiteSeeds(swToken) {
  return getAccountWisePoNumbers(swToken).then((resp) => {
    const rows = Array.isArray(resp.body?.data) ? resp.body.data : [];

    // The entire self-healing story rests on `order_id` being present in this
    // payload. If AccountWise ever stops returning it, every row parses as "not
    // ours", the sweep silently becomes a no-op, and seeds accumulate forever
    // with nothing in the log to say so. Say it out loud instead.
    if (rows.length && !rows.some((r) => r?.order_id)) {
      const warning =
        `sweepSuiteSeeds: ${rows.length} purchase order(s) came back from ` +
        `GET ${getPurchaseBaseUrl()}/purchaseOrder/numbers and NONE carries an order_id. ` +
        'Seed cleanup keys off that field, so it is now a no-op and seeds will accumulate on ' +
        'the tenant. Check whether AccountWise changed the payload shape.';
      Cypress.log({ name: 'sweepSuiteSeeds', message: warning });
      // eslint-disable-next-line no-console
      console.warn(warning);
    }

    const minAge = getSeedSweepMinAgeMs();
    const now = Date.now();
    const ours = [];
    const foreign = [];

    rows.forEach((row) => {
      const parsed = parseSeedOrderId(row?.order_id);
      if (!parsed) return;
      const isOwnRun = parsed.runId !== null && parsed.runId === RUN_ID;
      const isStale = parsed.createdAt === null || now - parsed.createdAt >= minAge;
      (isOwnRun || isStale ? ours : foreign).push(row);
    });

    if (ours.length) {
      Cypress.log({
        name: 'sweepSuiteSeeds',
        message: `Removing ${ours.length} leftover seed(s): ${ours.map((r) => r.purchase_order_number).join(', ')}`,
      });
    }
    if (foreign.length) {
      Cypress.log({
        name: 'sweepSuiteSeeds',
        message:
          `Leaving ${foreign.length} recent seed(s) from another run alone: ` +
          `${foreign.map((r) => r.purchase_order_number).join(', ')}. They are younger than ` +
          `${minAge / 60000} minute(s), so a concurrent spec may still be asserting on them.`,
      });
    }

    ours.forEach((r) => deleteAccountWisePo(swToken, r.id));
    // cy.wrap, not a bare number: cy.request commands were queued just above, so
    // returning a synchronous value here trips Cypress's mixing-async-and-sync
    // guard and fails the whole before() hook.
    return cy.wrap(ours.length, { log: false });
  });
}

/**
 * Delete a seed and THEN skip the current test.
 *
 * Cypress's `this.skip()` aborts the test and skips the remaining hooks —
 * including `afterEach` AND `after` — so a seed created before the skip is never
 * torn down. That leaked three AccountWise purchase orders per run until this
 * existed. Always clean up explicitly on the skip path; never rely on a hook.
 *
 * Call as `skipAfterCleanup.call(this, token, po, 'reason')` from a
 * `function () {}` callback, so `this` is the Mocha context.
 */
export function skipAfterCleanup(swToken, po, message) {
  const ctx = this;
  cy.log(`SKIPPED — ${message}`);
  return deleteAccountWisePo(swToken, po?.id).then(() => {
    ctx.skip();
  });
}

/**
 * Does StockWise already hold `poNumber` with status `Closed`?
 *
 * The close=false lane hard-excludes any number that is Closed in StockWise's
 * own table, REGARDLESS of what AccountWise reports. Because AccountWise
 * restarts its numbering at PO-0001 whenever its tenant is emptied, its
 * generated number frequently lands on a purchase order QA already closed — and
 * the AccountWise seed then legitimately does not appear in the open lane.
 *
 * Any TC whose subject is the open lane must check this first and skip, so the
 * environment collision is never misreported as the defect it happens to
 * resemble. (This exclusion is `SW-AWPO-API-TC11`'s own subject.)
 */
export function stockWiseHoldsClosedPo(swToken, poNumber) {
  return getStockWisePoDetail(swToken, poNumber).then((detail) => {
    const row = detail.body?.data ?? null;
    return Boolean(row?.poNumber) && row.status === 'Closed';
  });
}

/** Read a StockWise PO back by number. Raw response — 404/semantic errors are data. */
export function getStockWisePoDetail(swToken, poNumber) {
  return cy.request({
    method: 'GET',
    url: `${getStockWiseApiUrl()}/purchase-orders/po-number-detail-by-po/${encodeURIComponent(poNumber)}`,
    headers: { Authorization: `Bearer ${swToken}` },
    failOnStatusCode: false,
    timeout: 60000,
  });
}
