/**
 * AccountWise → StockWise Purchase-Order Visibility — API (SW-AWPO-API-TC01..13)
 * =============================================================================
 * Test plan: cypress/qa/testPlans/purchaseOrder/AccountWisePoIntegration/plan.md
 *
 * The seam under test is a PULL, not a push: there is no webhook and no nightly
 * sync. On every call to StockWise's
 *
 *   GET /excel/po-numbers            (Backend/src/modules/import/import.service.ts)
 *
 * ImportService.getPoList() resolves the caller's org-specific AccountWise
 * purchase API base from IAM, FORWARDS THE CALLER'S OWN BEARER to
 *
 *   GET {purchase.<host>/v1}/purchaseOrder/numbers
 *
 * racing it against a 5-second timeout, and merges those rows with StockWise's
 * own `purchaseOrders` table into one flat list. The push-side counterpart is
 *
 *   POST /purchase-orders/create/ingest   (Backend/src/modules/poDetail/…)
 *
 * AUTH — one token, not two. purchase-service mounts the same IAM Keycloak
 * guard StockWise does, so the bearer from cy.login() authenticates against BOTH
 * systems. No AccountWise credentials are involved (that is the INVOICE service,
 * used by the Work Order tests — see cypress/support/helpers/accountwise.js).
 *
 * SEEDING — every seed is created through AccountWise's real purchase API and
 * deleted in afterEach(). The PO number is server-generated by AccountWise, so it
 * is read out of the create response and never predicted.
 *
 * ── SEED ISOLATION: WHY MOST TCs SET metadata EXPLICITLY ─────────────────────
 * Defect D1 (pending.md §1) makes the close=false lane return 500 whenever ANY
 * AccountWise PO with NULL metadata exists. Left unmanaged that would mask every
 * other condition in this file behind one unrelated defect. So each TC seeds the
 * narrowest thing it needs:
 *
 *   • TC01 and TC09 seed NULL metadata deliberately — TC01 because that is what
 *     a real buyer's purchase order looks like, TC09 because null metadata IS
 *     its subject. Both are D1's regression guards: they go RED whenever D1
 *     reproduces and GREEN when it does not, with no edit either way.
 *   • Every other TC seeds `metadata: { stockWiseStatus: 'open' }`, which is a
 *     valid open purchase order by the same filter, so its own condition is what
 *     decides the result. This is the convention plan.md §6.3 already mandates
 *     for TC07, generalised.
 *
 * ⚠️ TC01 and TC09 briefly degrade shared QA while their seed exists (every PO
 * picker in the org returns 500). Seeds are therefore torn down in afterEach,
 * not just after, so the window is seconds — and neither carries @smoke.
 * `cy:run:smoke` globs the whole of cypress/e2e, so tagging them would fire that
 * org-wide 500 on every smoke run against a SHARED environment. They stay
 * @regression-only until the one-line D1 guard lands (pending.md §1 / D1); TC12,
 * which touches no AccountWise record at all, keeps its @smoke tag.
 */

import {
  probeAccountWisePurchaseApi,
  getAccountWiseVendorRef,
  createAccountWisePo,
  deleteAccountWisePo,
  setAccountWiseStockWiseStatus,
  AW_STOCKWISE_STATUS,
  ensureStockWiseCounterpart,
  cancelAccountWisePo,
  deleteStockWisePo,
  ingestAccountWisePo,
  getStockWisePoDetail,
  getStockWisePoList,
  getStockWisePoListResponse,
  stockWiseHoldsClosedPo,
  skipAfterCleanup,
  sweepSuiteSeeds,
  poListIncludes,
  poListEntry,
  poListCount,
  poListNames,
  getPurchaseBaseUrl,
} from '../../support/helpers/accountWisePurchaseOrders';

import poFixture from '../../fixtures/accountWisePurchaseOrder.json';

describe('AccountWise → StockWise Purchase-Order Visibility API', { tags: ['@regression'] }, () => {
  let authToken;
  let vendorRef = null;
  let suiteSkipReason = null;

  // Disposable resources, torn down after EVERY test. A leaked AccountWise PO is
  // visible to every later run's close=true list and would flip TC08 (dedup) and
  // TC10 (sort); a leaked NULL-metadata one also 500s the close=false lane
  // org-wide until it is removed.
  let awSeeds = [];
  let swSeeds = [];

  // Partition constants live in the fixture, not inline in two specs.
  const OPEN_METADATA = { metadata: poFixture.metadata.epExplicitOpen };

  /** Seed an AccountWise PO and register it for teardown. */
  const seedAw = (opts = {}) =>
    createAccountWisePo(authToken, { vendorRef, status: poFixture.status.epPending, ...opts }).then(
      (po) => {
        awSeeds.push(po);
        return po;
      },
    );

  before(() => {
    cy.login().then((token) => {
      authToken = token;
      expect(authToken, 'a IAM bearer is required for both StockWise and AccountWise').to.exist;
    });

    // Self-heal before anything else: a previous run that ended on a skip may
    // have left seeds behind (this.skip() bypasses afterEach AND after), and a
    // stale NULL-metadata seed would 500 the open lane for every test below.
    cy.then(() => sweepSuiteSeeds(authToken));

    // Gate 1 — reachability. StockWise degrades SILENTLY when AccountWise is
    // unreachable (5s timeout -> StockWise-only list), so without this an
    // AccountWise outage would surface as "the PO is not in the list" on all 13
    // tests instead of naming the environment. plan.md §8 risk 1.
    cy.then(() => probeAccountWisePurchaseApi(authToken)).then(({ reachable, reason }) => {
      if (!reachable) suiteSkipReason = reason;
    });

    // Gate 2 — a vendor reference. AccountWise requires a real vendor_id on
    // create and the UUIDs are per-tenant; a synthetic one is rejected with a
    // 500, which would read as an outage rather than a missing precondition.
    cy.then(() => (suiteSkipReason ? null : getAccountWiseVendorRef(authToken))).then((ref) => {
      if (suiteSkipReason) return;
      if (!ref) {
        suiteSkipReason =
          `The AccountWise tenant behind ${getPurchaseBaseUrl()} has no vendor to reference, ` +
          'so this suite cannot seed a purchase order (AccountWise rejects a synthetic ' +
          'vendor_id with a 500). Create one vendor on the tenant and re-run.';
        return;
      }
      vendorRef = ref;
    });
  });

  beforeEach(function () {
    if (suiteSkipReason) {
      cy.log(`SKIPPED — ${suiteSkipReason}`);
      this.skip();
    }
  });

  afterEach(() => {
    if (!authToken) return;
    awSeeds.forEach((po) => deleteAccountWisePo(authToken, po.id));
    swSeeds.forEach((poNumber) => deleteStockWisePo(authToken, poNumber));
    awSeeds = [];
    swSeeds = [];
  });

  // Safety net. `this.skip()` aborts a test AND its remaining hooks, so a seed
  // created just before a skip never reaches afterEach. Sweep by order_id prefix
  // rather than replaying awSeeds, which that same skip may have orphaned.
  after(() => {
    if (!authToken) return;
    swSeeds.forEach((poNumber) => deleteStockWisePo(authToken, poNumber));
    swSeeds = [];
    sweepSuiteSeeds(authToken);
  });

  // ───────────────────────────────────────────────────────────────────────────
  // GET /excel/po-numbers — visibility, attribution, costing
  // ───────────────────────────────────────────────────────────────────────────

  // EP — the happy-path partition: a purchase order in AccountWise's ordinary
  // post-creation status ('Pending') with NO metadata, which is exactly what a
  // buyer's purchase order looks like. One value per partition is sufficient;
  // the Draft partition is TC04's.
  //
  // ⚠️ D1 REGRESSION GUARD — read the status, not this comment, for today's
  // result. import.service.ts:247 dereferences `record.metadata.stockWiseStatus`
  // unguarded, so a NULL-metadata seed can make GET /excel/po-numbers return 500
  // for the whole org. This TC therefore goes RED whenever D1 reproduces and
  // GREEN when it does not — no edit either way.
  //
  // On shared QA it most often SKIPS before reaching that assertion, because
  // AccountWise's regenerated number collides with a purchase order StockWise
  // already holds as Closed (see the guard below). A skip is an environment
  // signal, not a verdict on D1.
  //
  // Do NOT "fix" this by seeding metadata — the absence of metadata is the
  // real-world condition under test.
  it('SW-AWPO-API-TC01 — a purchase order created in AccountWise shows up in StockWise purchase-order list', function () {
    let seededPoNumber;

    // Read the list BEFORE seeding so the assertion proves the PO ARRIVED,
    // rather than that some AccountWise PO happens to exist already.
    getStockWisePoList(authToken)
      .then((before) => {
        expect(
          poListIncludes(before, 'PO-DOES-NOT-EXIST-YET'),
          'sanity: the pre-seed list must not contain a name we never created',
        ).to.eq(false);
        return seedAw();
      })
      .then((po) => {
        seededPoNumber = po.purchase_order_number;
        return stockWiseHoldsClosedPo(authToken, seededPoNumber);
      })
      .then(function guardCollision(alreadyClosedLocally) {
        // Guard the ENVIRONMENT collision before asserting the defect: AccountWise
        // restarts numbering at PO-0001, so its number can land on a purchase
        // order QA already closed, which the open lane hard-excludes by design
        // (that rule is TC11's subject). Skipping keeps this failure honest.
        if (alreadyClosedLocally) {
          return skipAfterCleanup.call(
            this,
            authToken,
            awSeeds[awSeeds.length - 1],
            `StockWise already holds "${seededPoNumber}" with status Closed, so the open lane ` +
              'excludes it by design. Re-run once AccountWise numbering has moved past the ' +
              'purchase orders QA already holds.',
          );
        }
        // No import, no upload, no sync step in StockWise — the very next read
        // of the merged list is what has to surface it.
        return getStockWisePoList(authToken);
      })
      .then((after) => {
        expect(
          poListIncludes(after, seededPoNumber),
          `AccountWise purchase order "${seededPoNumber}" must appear in StockWise's merged ` +
            'PO list with no StockWise-side import. If it does not, the most likely cause is ' +
            'NOT a filter bug: it is that the org this suite seeded into is not the org ' +
            'StockWise resolves its AccountWise base for (plan.md §8 risk 2). Check that ' +
            'GET {IAM}/v1/me/home returns an AccountWise card for this account before ' +
            'investigating ImportService.getPoList().',
        ).to.eq(true);
      });
  });

  // EP — the attribution partition. `source=true` changes the element shape to
  // { name, source }; AccountWise wins on overlap (that collision case is TC08).
  it('SW-AWPO-API-TC02 — StockWise labels that purchase order as coming from AccountWise', () => {
    seedAw({ overrides: OPEN_METADATA })
      .then((po) =>
        // close=true on purpose: this TC's subject is attribution, not the open lane.
        // The full lane applies neither the stockWiseStatus filter nor the
        // StockWise-Closed exclusion, so neither defect D1 nor an AccountWise/
        // StockWise number collision can mask the thing being asserted.
        getStockWisePoList(authToken, { close: true, source: true }).then((list) => ({ po, list })),
      )
      .then(({ po, list }) => {
        const entry = poListEntry(list, po.purchase_order_number);
        expect(
          entry,
          `"${po.purchase_order_number}" must be present when source attribution is requested`,
        ).to.exist;
        expect(
          entry.source,
          'a purchase order that exists only in AccountWise must be attributed to AccountWise, ' +
            'otherwise the Reports badge credits StockWise for another system record',
        ).to.eq('AccountWise');
      });
  });

  // EP — the costing partition. `cost=true` yields { name, cost } where cost is
  // AccountWise's own total_amount, carried through unchanged.
  it('SW-AWPO-API-TC03 — StockWise shows the purchase order AccountWise order total as its cost', () => {
    seedAw({ overrides: OPEN_METADATA })
      .then((po) =>
        // close=true on purpose: this TC's subject is costing, not the open lane.
        // The full lane applies neither the stockWiseStatus filter nor the
        // StockWise-Closed exclusion, so neither defect D1 nor an AccountWise/
        // StockWise number collision can mask the thing being asserted.
        getStockWisePoList(authToken, { close: true, cost: true }).then((list) => ({ po, list })),
      )
      .then(({ po, list }) => {
        const entry = poListEntry(list, po.purchase_order_number);
        expect(entry, `"${po.purchase_order_number}" must be present when costs are requested`).to
          .exist;
        // Guard the operands first: if AccountWise ever stops echoing
        // total_amount, both sides become NaN and `expect(NaN).to.eq(NaN)` fails
        // with "expected NaN to equal NaN" plus the costing message below —
        // sending the reader after a StockWise bug that does not exist.
        expect(
          Number.isFinite(Number(po.total_amount)),
          `AccountWise must echo a numeric total_amount on create (got ${JSON.stringify(po.total_amount)})`,
        ).to.eq(true);
        expect(
          Number.isFinite(Number(entry.cost)),
          `StockWise must report a numeric cost for "${po.purchase_order_number}" (got ${JSON.stringify(entry.cost)})`,
        ).to.eq(true);
        expect(
          Number(entry.cost),
          'the cost StockWise reports must be the AccountWise total_amount, unconverted — a ' +
            'mismatch means the finance figure shown to warehouse staff disagrees with the order ' +
            'they are receiving against',
        ).to.eq(Number(po.total_amount));
      });
  });

  // EP — the Draft partition. AccountWise's getAllPurchaseOrderNumbers() applies
  // no status filter, so a Draft purchase order reaches StockWise too.
  // NOTE: whether the RECEIVING lane should then offer it is defect D2's
  // question (pending.md §1) — this TC pins arrival only, per plan.md §9.
  it('SW-AWPO-API-TC04 — a purchase order still in Draft in AccountWise also reaches StockWise', () => {
    seedAw({ status: poFixture.status.epDraft, overrides: OPEN_METADATA })
      .then((po) =>
        // close=true on purpose: this TC's subject is whether a Draft purchase order ARRIVES at all, not the open lane.
        // The full lane applies neither the stockWiseStatus filter nor the
        // StockWise-Closed exclusion, so neither defect D1 nor an AccountWise/
        // StockWise number collision can mask the thing being asserted.
        getStockWisePoList(authToken, { close: true }).then((list) => ({ po, list })),
      )
      .then(({ po, list }) => {
        expect(
          poListIncludes(list, po.purchase_order_number),
          'AccountWise applies no status filter when listing purchase-order numbers, so Draft ' +
            `purchase order "${po.purchase_order_number}" is expected to arrive in StockWise`,
        ).to.eq(true);
      });
  });

  // ───────────────────────────────────────────────────────────────────────────
  // The close=false / close=true decision table
  // ───────────────────────────────────────────────────────────────────────────

  // Decision table — condition: AccountWise's stockWiseStatus flag; lane:
  // close=false. Column: flag='closed' -> excluded from the open lane. The
  // mutation is paired with its inverse in the test body, and the seed is
  // deleted outright in afterEach as the safety net.
  it('SW-AWPO-API-TC05 — once StockWise marks the purchase order closed, it drops out of the open purchase-order list', function () {
    let po;
    seedAw({ overrides: OPEN_METADATA })
      .then((created) => {
        po = created;
        return stockWiseHoldsClosedPo(authToken, po.purchase_order_number);
      })
      .then(function guardCollision(alreadyClosedLocally) {
        if (alreadyClosedLocally) {
          return skipAfterCleanup.call(
            this,
            authToken,
            po,
            `StockWise already holds "${po.purchase_order_number}" as Closed, so the open lane ` +
              'excludes it by design (that exclusion is TC11 subject) and this result would be ' +
              'unreadable.',
          );
        }
        return getStockWisePoList(authToken, { close: false });
      })
      .then((openBefore) => {
        expect(
          poListIncludes(openBefore, po.purchase_order_number),
          'precondition: the open purchase order must be in the open lane before it is closed',
        ).to.eq(true);
        return setAccountWiseStockWiseStatus(authToken, po.id, AW_STOCKWISE_STATUS.CLOSED);
      })
      .then(() => getStockWisePoList(authToken, { close: false }))
      .then((openAfter) => {
        expect(
          poListIncludes(openAfter, po.purchase_order_number),
          `"${po.purchase_order_number}" is closed for StockWise, so it must no longer be offered ` +
            'in the open lane that the receiving screens use',
        ).to.eq(false);
        // Inverse, in-body: restore the flag so the record is unchanged even if
        // teardown were to fail.
        return setAccountWiseStockWiseStatus(authToken, po.id, AW_STOCKWISE_STATUS.OPEN);
      });
  });

  // Decision table — SAME condition, the OTHER lane: close=true applies neither
  // the stockWiseStatus filter nor the StockWise-Closed exclusion.
  //
  // ⚠️ EXPECTED RED — defect D3 (pending.md §1). This TC cannot reach its own
  // assertion: AccountWise's POST /v1/purchaseOrder/close returns 500 for BOTH
  // accepted values (`open` and `close`), so the arrange step fails. The failure
  // message comes from the helper ("AccountWise must accept stockWiseStatus…") —
  // that is D3, not a payload bug in this test.
  it('SW-AWPO-API-TC06 — that same closed purchase order is still listed when the caller asks for every purchase order', () => {
    let po;
    seedAw({ overrides: OPEN_METADATA })
      .then((created) => {
        po = created;
        return setAccountWiseStockWiseStatus(authToken, po.id, AW_STOCKWISE_STATUS.CLOSED);
      })
      .then(() => getStockWisePoList(authToken, { close: true }))
      .then((allPos) => {
        expect(
          poListIncludes(allPos, po.purchase_order_number),
          `the full list must still contain closed purchase order "${po.purchase_order_number}" — ` +
            'Reports and history depend on closed purchase orders remaining visible',
        ).to.eq(true);
        return setAccountWiseStockWiseStatus(authToken, po.id, AW_STOCKWISE_STATUS.OPEN);
      });
  });

  // State transition — Pending -> Cancelled in AccountWise. A cancelled purchase
  // order is terminal: nothing may be received against it, so it must leave the
  // receiving lane while remaining in the historical one. Cancel has NO inverse
  // in purchase-service, so this seed is created for this test alone.
  //
  // ⚠️ D2 REGRESSION GUARD — StockWise never reads AccountWise's document
  // `status`, so a cancelled purchase order is still offered for receiving. RED
  // whenever D2 reproduces; on shared QA it often SKIPS first on the number
  // collision (see the guard below), which is an environment signal, not a
  // verdict. Seeded with explicit metadata so D1 cannot mask D2.
  it('SW-AWPO-API-TC07 — cancelling the purchase order in AccountWise withdraws it from the receiving list but not the full list', function () {
    let po;
    seedAw({ overrides: OPEN_METADATA })
      .then((created) => {
        po = created;
        return stockWiseHoldsClosedPo(authToken, po.purchase_order_number);
      })
      .then(function guardCollision(alreadyClosedLocally) {
        if (alreadyClosedLocally) {
          return skipAfterCleanup.call(
            this,
            authToken,
            po,
            `StockWise already holds "${po.purchase_order_number}" as Closed, so the open lane ` +
              'excludes it by design (that exclusion is TC11 subject) and this result would be ' +
              'unreadable.',
          );
        }
        return getStockWisePoList(authToken, { close: false });
      })
      .then((before) => {
        expect(
          poListIncludes(before, po.purchase_order_number),
          'precondition: the purchase order must be offered for receiving before it is cancelled',
        ).to.eq(true);
        return cancelAccountWisePo(authToken, po.id);
      })
      .then(() => getStockWisePoList(authToken, { close: false }))
      .then((receivingAfter) => {
        expect(
          poListIncludes(receivingAfter, po.purchase_order_number),
          `"${po.purchase_order_number}" is Cancelled in AccountWise, so it must not be offered ` +
            'for receiving — stock received against a revoked order reconciles against nothing. ' +
            'EXPECTED RED against defect D2 until StockWise gates on AccountWise document status.',
        ).to.eq(false);
        return getStockWisePoList(authToken, { close: true });
      })
      .then((fullAfter) => {
        expect(
          poListIncludes(fullAfter, po.purchase_order_number),
          'the cancelled purchase order must remain in the full list for reporting and history',
        ).to.eq(true);
      });
  });

  // Decision table — the same purchase-order number on BOTH sides. The dedup Map
  // is keyed on name.trim().toLowerCase() and populated StockWise-first,
  // AccountWise-second, so AccountWise's entry overwrites StockWise's.
  it('SW-AWPO-API-TC08 — a purchase-order number that exists in both systems is listed once, credited to AccountWise', () => {
    let po;
    seedAw({ overrides: OPEN_METADATA })
      .then((created) => {
        po = created;
        // AccountWise generates its own number, so the collision must be made on
        // the StockWise side. On shared QA that collision usually ALREADY exists
        // (AccountWise restarts at PO-0001 and StockWise holds native purchase
        // orders in that range), so reuse it rather than failing on a duplicate —
        // and never delete a row this suite did not create.
        return ensureStockWiseCounterpart(authToken, created.purchase_order_number);
      })
      .then(({ mode }) => {
        if (mode === 'created') swSeeds.push(po.purchase_order_number);
        // close=true: the full lane applies neither the stockWiseStatus filter
        // nor the StockWise-Closed exclusion, so whichever status the reused
        // counterpart happens to carry cannot change what dedup is asked to do.
        return getStockWisePoList(authToken, { close: true, source: true });
      })
      .then((list) => {
        expect(
          poListCount(list, po.purchase_order_number),
          `"${po.purchase_order_number}" exists in both systems and must be de-duplicated to a ` +
            'single entry — a warehouse admin must not be offered the same purchase order twice',
        ).to.eq(1);
        expect(
          poListEntry(list, po.purchase_order_number).source,
          'on collision AccountWise wins: its entry is written into the dedup map last',
        ).to.eq('AccountWise');
      });
  });

  // Error guessing — AccountWise's `metadata` is a nullable jsonb column and
  // StockWise reads through it. This is the permanent regression guard for D1.
  //
  // ⚠️ D1 REGRESSION GUARD. Deliberately asserts the intended behaviour (the
  // list still works), per plan.md §8 risk 6: "If it fails, that is a real
  // defect, not a test bug — report it, do not add a workaround."
  //
  // Three outcomes, all meaningful: GREEN = a NULL-metadata purchase order went
  // through the filter and the lane survived (observed 2026-08-18). RED = D1 is
  // reproducing. SKIPPED/INCONCLUSIVE = the purchase order never reached
  // StockWise, so nothing was proven — see the witness step below.
  it('SW-AWPO-API-TC09 — a purchase order created in AccountWise with no metadata does not break the purchase-order list', function () {
    let baselineNames;
    let seeded;

    getStockWisePoList(authToken, { close: false })
      .then((before) => {
        baselineNames = poListNames(before);
        // No metadata override: this is the condition under test.
        return seedAw();
      })
      .then((po) => {
        seeded = po;
        // Prove the AccountWise rows actually reached StockWise before judging
        // the open lane. close=true never touches `metadata`, so it is a clean
        // witness. Without this the TC PASSES SPURIOUSLY: when StockWise's
        // server-to-server call to AccountWise fails it returns the
        // StockWise-only list with a 200, the null-metadata row never reaches
        // the filter, and "200" would look like proof the guard exists.
        return getStockWisePoList(authToken, { close: true });
      })
      .then(function witness(fullLane) {
        if (!poListIncludes(fullLane, seeded.purchase_order_number)) {
          return skipAfterCleanup.call(
            this,
            authToken,
            seeded,
            `INCONCLUSIVE — "${seeded.purchase_order_number}" did not reach StockWise at all ` +
              '(absent even from close=true), so its metadata was never put through the filter. ' +
              "StockWise's call to AccountWise most likely failed and degraded to the " +
              'StockWise-only list. Re-run; do not read this as evidence that D1 is fixed.',
          );
        }
        // The raw response, so the assertion below belongs to the TEST rather
        // than to the helper — otherwise the failure would read as a helper error.
        return getStockWisePoListResponse(authToken, { close: false });
      })
      .then((resp) => {
        expect(
          resp.status,
          'a purchase order with no metadata must not break the merged list. ' +
            'import.service.ts:247 dereferences record.metadata.stockWiseStatus without a null ' +
            'guard, so one such purchase order returns 500 for the whole org, taking out every ' +
            'default PO picker — not merely hiding this one record.',
        ).to.eq(200);

        const namesAfter = poListNames(resp.body?.data?.poList ?? []);
        const lost = baselineNames.filter((n) => !namesAfter.includes(n));
        expect(
          lost,
          'the purchase orders that were visible beforehand must still be visible afterwards',
        ).to.deep.eq([]);
      });
  });

  // Use case — the controller sorts the merged list before returning it. The
  // element shape differs by variant (plain strings by default), so this asserts
  // the default variant's accessor.
  it('SW-AWPO-API-TC10 — StockWise returns the combined purchase-order list in alphabetical order', () => {
    seedAw({ overrides: OPEN_METADATA })
      .then(() => getStockWisePoList(authToken))
      .then((list) => {
        expect(
          list.length,
          'the environment must have more than one purchase order for ordering to mean anything',
        ).to.be.greaterThan(1);
        const names = list.map((entry) => (typeof entry === 'object' ? entry?.name : entry));
        const sorted = [...names].sort((a, b) => String(a).localeCompare(String(b)));
        expect(
          names,
          'the merged list is sorted in the controller with localeCompare; an unsorted list means ' +
            'the picker shows AccountWise and StockWise purchase orders in arrival order instead',
        ).to.deep.eq(sorted);
      });
  });

  // Decision table — the OTHER condition on the open lane: StockWise's own
  // status. A purchase order that is Closed in StockWise is hard-excluded even
  // while AccountWise still reports it open.
  it('SW-AWPO-API-TC11 — a purchase order closed inside StockWise stays hidden even while AccountWise still reports it open', function () {
    let po;
    seedAw({ overrides: OPEN_METADATA })
      .then((created) => {
        po = created;
        return ensureStockWiseCounterpart(authToken, created.purchase_order_number, {
          requiredStatus: 'Closed',
        });
      })
      .then(function handleCounterpart({ mode, status }) {
        if (mode === 'unusable') {
          // A StockWise row already owns this number but is not Closed. Forcing
          // it would mutate shared data — closePurchaseOrder also writes
          // stockWiseStatus back into AccountWise — so report the environment
          // and skip rather than damage somebody else's purchase order.
          return skipAfterCleanup.call(
            this,
            authToken,
            po,
            `StockWise already has "${po.purchase_order_number}" with status "${status}", and this ` +
              'TC needs it Closed. AccountWise restarts its numbering at PO-0001, so its generated ' +
              'number collides with the purchase orders QA already holds.',
          );
        }
        if (mode === 'created') swSeeds.push(po.purchase_order_number);
        return getStockWisePoList(authToken, { close: false });
      })
      .then((openLane) => {
        expect(
          poListIncludes(openLane, po.purchase_order_number),
          'StockWise is the source of truth for receiving status: ' +
            `"${po.purchase_order_number}" is Closed locally, so it must stay out of the open lane ` +
            'even though AccountWise still reports stockWiseStatus=open',
        ).to.eq(false);
      });
  });

  // ───────────────────────────────────────────────────────────────────────────
  // POST /purchase-orders/create/ingest — the push side
  // ───────────────────────────────────────────────────────────────────────────

  // Use case — AccountWise pushes a purchase order into StockWise directly.
  // No AccountWise record is involved, so this TC is independent of D1/D2.
  it('SW-AWPO-API-TC12 — StockWise creates a local purchase-order record when AccountWise pushes one to the ingest endpoint', { tags: ['@smoke'] }, () => {
    const poNumber = `CYP-AWPO-INGEST-${Date.now()}`;
    const payload = { poNumber, expectedQuantity: 7, incomingCost: 123.45 };

    ingestAccountWisePo(authToken, payload)
      .then((resp) => {
        swSeeds.push(poNumber);
        expect(
          resp.status,
          `the ingest endpoint must create "${poNumber}" ` +
            `(body: ${JSON.stringify(resp.body).slice(0, 300)})`,
        ).to.be.within(200, 299);
        return getStockWisePoDetail(authToken, poNumber);
      })
      .then((detail) => {
        const row = detail.body?.data ?? detail.body;
        expect(row, 'the pushed purchase order must be readable back from StockWise').to.exist;
        expect(
          Number(row.expectedQuantity),
          'the pushed expected quantity must be stored, not defaulted — it is what the receiving ' +
            'screens reconcile against',
        ).to.eq(payload.expectedQuantity);
        expect(Number(row.incomingCost), 'the pushed cost must be stored unchanged').to.eq(
          payload.incomingCost,
        );
      });
  });

  // Error guessing — the same purchase order pushed twice. The service checks for
  // an existing row and throws BadRequestException, so this is a Joi-passing
  // request rejected by the service (plan.md §6 convention 2).
  it('SW-AWPO-API-TC13 — pushing the same purchase order twice is rejected instead of creating a duplicate', () => {
    const poNumber = `CYP-AWPO-DUP-${Date.now()}`;
    const payload = { poNumber, expectedQuantity: 3, incomingCost: 10 };

    ingestAccountWisePo(authToken, payload)
      .then((first) => {
        swSeeds.push(poNumber);
        expect(
          first.status,
          'the first push must succeed so the duplicate has something to collide with',
        ).to.be.within(200, 299);
        // Re-push the identical payload rather than mutating anything new.
        return ingestAccountWisePo(authToken, payload);
      })
      .then((second) => {
        expect(second.status, 'a duplicate push must not 5xx — it is a client error').to.be.lessThan(
          500,
        );
        expect(
          second.body?.success === false || second.body?.error || second.status >= 400,
          `pushing "${poNumber}" twice must be rejected; silently creating a second row would ` +
            'split receiving across two records for one AccountWise order',
        ).to.be.ok;
        return getStockWisePoDetail(authToken, poNumber);
      })
      .then((detail) => {
        const row = detail.body?.data ?? detail.body;
        const readBack = Array.isArray(row) ? row[0]?.poNumber : row?.poNumber;
        expect(readBack, 'exactly one record must remain for that purchase-order number').to.eq(
          poNumber,
        );
      });
  });

  // Error guessing — the ingest route is the ONE endpoint this module owns end
  // to end, and it carries no explicit @UseGuards: it is protected only by the
  // globally-registered guard. That is exactly the kind of protection a refactor
  // removes silently, so assert it directly. Sends NO Authorization header, the
  // mirror of the suite's @Public() contract convention (cypress/qa/SKILL.md §6).
  it('SW-AWPO-API-TC14 — the ingest endpoint rejects an unauthenticated push', () => {
    const poNumber = `CYP-AWPO-NOAUTH-${Date.now()}`;

    ingestAccountWisePo(null, { poNumber, expectedQuantity: 1, incomingCost: 1 }, { noAuth: true })
      .then((resp) => {
        expect(
          resp.status,
          'an unauthenticated push must be refused. AccountWise pushing purchase orders into ' +
            'StockWise is a privileged write; if this ever returns 2xx, anyone on the network can ' +
            'create purchase orders.',
        ).to.be.oneOf([401, 403]);
        // Verify with the ADMIN token, not `null`. Reading back unauthenticated
        // would itself be refused, so `row` would be empty no matter what the
        // ingest route did — the assertion could never fail and would prove
        // nothing about whether a row was written.
        return getStockWisePoDetail(authToken, poNumber);
      })
      .then((detail) => {
        const row = detail.body?.data ?? null;
        expect(
          row?.poNumber,
          `"${poNumber}" must not exist after a rejected push — a guard that refuses the caller ` +
            'but still writes the row would be worse than no guard at all',
        ).to.not.eq(poNumber);
      });
  });
});
